### PR TITLE
CFY-4762 - customizable management workers logging level

### PR DESCRIPTION
**Pull request by isaac-s**

### CODE REVIEW

**Comment by dankilman** [comment]
PR looks good.
Please restore the default back to `debug` and open a JIRA to consider changing it to `info`.
It should be noted that in 3.4, only celery specific logs will go to the celery.logs. All application/cloudify/etc... logs will go to to a different place.

**Comment by isaac-s** [comment]
Default changed back to `debug` in manager blueprints.

The (commented-out) setting in the input templates remained as `info`. I'd like to keep it like that as some sort of a "hint" (unless we have a convention whereby the inputs template must contain the defaults commented out).

Separate JIRA for considering `info` as the default: https://cloudifysource.atlassian.net/browse/CFY-4781

**Comment by dankilman** [comment]
I would prefer it if we restore the commented out part to "debug" as well

**Comment by dankilman** [comment]
also, please squash your commits after you are done

**Comment by nir0s** [comment]
Isaac, please provide a very clear description of what this does. While it is obvious to us, users who will be looking at the inputs file have no idea what the management worker is so they will not know what the log level will be used for.

Thanks.

**Comment by isaac-s** [comment]
@nir0s done.

**Comment by nir0s** [comment]
Sorry. Again? :)

**Pull request closed without merging**
